M48
; DRILL file KiCad 10.0.5 date 2026-08-07T21:44:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-07T21:44:13+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
%
G90
G05
T1
X45.084Y-53.27
X159.5Y-53.326
T2
X42.48Y-73.29
X42.48Y-79.07
M30
